image: docker:latest

services:
  - docker:dind

stages:
  - build

before_script:
  - export IMAGE_TAG="$CI_BUILD_REF_NAME"
  - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" $CI_REGISTRY

build-web:
  stage: build
  script:
    - docker pull "$CI_REGISTRY_IMAGE:$IMAGE_TAG" || docker build --pull -f docker/Dockerfile --build-arg REVISION=$IMAGE_TAG -t "$CI_REGISTRY_IMAGE:$IMAGE_TAG" .
    - docker tag  "$CI_REGISTRY_IMAGE:$IMAGE_TAG" "$CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME"
    - docker push "$CI_REGISTRY_IMAGE:$IMAGE_TAG"
  only:
    - /^\d+\.\d+\.\d+$/
