swagger: '2.0'
info:
  description: API para la integración de servicios externos con la aplicación móvil de "Mi Universidad"
  version: 1.0.0
  title: Mi Universidad API
  # put the contact info for your development or API team
  contact:
    email: tanoinc@gmail.com

  license:
    name: GNU GPL v3
    url: https://www.gnu.org/licenses/gpl-3.0.en.html

# tags are used for organizing operations
tags:
- name: novedades
  description: Operaciones relacionadas con las novedades en el newsfeed de la aplicación móvil
- name: calendario
  description: Operaciones sobre los eventos del calendario
securityDefinitions:
  api_key:
    description: "Agrega el siguiente encabezado HTTP: Authorization: APIKEY {api_key}:{firma}. {api_key} es la identificación del servicio otorgado y {firma} es el contenido firmado con la clave secreta (api secret). Se utiliza HMAC con sha256 sobre todo el contenido de la solicitud, de la siguiente forma:"
    type: apiKey
    name: Authorization
    in: header
paths:
  /newsfeed:
    post:
      tags:
      - novedades
      security: 
      - api_key: []
      summary: Envía una nueva novedad
      operationId: NewsfeedController@create
      description: "Agrega una nueva novedad a los newsfeed de los usuarios interesados (a nivel de: destinatario, contexto y/o aplicación)"
      consumes:
      - application/json
      - application/x-www-form-urlencoded
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        description: Atributos de la novedad a crear
        required: true
        schema:
          $ref: '#/definitions/newsfeed_post'
      responses:
        200:
          description: "Novedad creada"
          schema:
            $ref: '#/definitions/newsfeed_post_response'
        401:
          description: "No autorizado"          
        403:
          description: "Acceso prohibido"
        422:
          description: "Error de validación"
        500:
          description: "Errores varios. Ver detalle en respuesta"
  /calendar_event:
    post:
      tags:
      - calendario
      security: 
      - api_key: []
      summary: Crea un nuevo evento en el calendario
      operationId: CalendarEventController@create
      description: "Agrega un nuevo evento al calendario de los usuarios interesados (a nivel de: destinatario, contexto y/o aplicación)"
      consumes:
      - application/json
      - application/x-www-form-urlencoded
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        description: Atributos del evento a crear
        required: true
        schema:
          $ref: '#/definitions/calendar_event_post'
      responses:
        200:
          description: "Evento creado"
          schema:
            $ref: '#/definitions/calendar_event_post_response'
        401:
          description: "No autorizado"          
        403:
          description: "Acceso prohibido"
        422:
          description: "Error de validación"
        500:
          description: "Errores varios. Ver detalle en respuesta"

    get:
      tags:
      - test
      summary: searches inventory
      operationId: searchInventory
      description: |
        By passing in the appropriate options, you can search for
        available inventory in the system
      produces:
      - application/json
      parameters:
      - in: query
        name: searchString
        description: pass an optional search string for looking up inventory
        required: false
        type: string
      - in: query
        name: skip
        description: number of records to skip for pagination
        type: integer
        format: int32
        minimum: 0
      - in: query
        name: limit
        description: maximum number of records to return
        type: integer
        format: int32
        minimum: 0
        maximum: 50
      responses:
        200:
          description: search results matching criteria
          schema:
            type: array
            items:
              $ref: '#/definitions/InventoryItem'
        400:
          description: bad input parameter

definitions:
  newsfeed:
    type: object
    properties:
      send_notification:
        type: integer
        example: 1
        enum: [0,1]        
        description: "Opcional. 1 = enviar notificacion, 0 = no enviar notificacion. Por defecto: 0"      
      global:
        type: integer
        example: 1
        enum: [0,1]
        description: "Opcional. 1 = novedades globales al servicio, 0 = no globales. Por defecto: 0"      
      title:
        type: string
        example: "Prueba!"
      content: 
        type: string
        example: "Esto es una prueba"
      updated_at:
        type: string
        example: '2017-08-25 00:10:11'
      created_at:
        type: string
        example: '2017-08-25 00:10:11'        
      id:
        type: integer
        example: 1134
  newsfeed_post_response:
    type: object
    properties:
      newsfeed:
        type: object
        $ref: '#/definitions/newsfeed'
      notification_push_data_uuid:
        type: string
        example: "e10adc-asda34-asdasdas-bbc"

  newsfeed_post:
    type: object
    required: 
    -  title
    -  content
    properties:
      title:
        type: string
        example: "Título de la novedad"
        maxLength: 150        
      content:
        type: string
        example: "Contenido del texto de la novedad"
      global:
        type: integer
        example: 1
        enum: [0,1]
        description: "Opcional. 1 = novedades globales al servicio, 0 = no globales. Por defecto: 0"
      send_notification:
        type: integer
        example: 1
        enum: [0,1]        
        description: "Opcional. 1 = enviar notificacion, 0 = no enviar notificacion. Por defecto: 0"
      recipients:
        type: array
        items:
          type: string      
        example: ["id_externo_1", "id_externo_2", "id_externo_3"]
        description: "Opcional. Destinatarios: Arreglo de IDs de los destinatarios de la novedad. Los IDs son locales del servicio, los enviados al asociar el usuario (valores externos a Mi Universidad)"
      context:
        type: string
        maxLength: 150
        pattern: "^[a-zA-Z0-9_-]*$"
        example: "matematica_1"
        description: "Opcional. Nombre único (alfanunmérico y guiones) identificatorio del contexto (en la aplicación llamados 'temas'). Si el contexto no existe, lo crea. Para crear nuevos contextos, se recomienda utilizar los parámetros: context_name y context_description."
      context_name:
        type: string
        maxLength: 150
        pattern: "^[a-zA-Z0-9_-]*$"
        example: "matematica_1"
        description: "Opcional (si se utiliza, 'context_description' es requerido). Nombre único (alfanunmérico y guiones) identificatorio del contexto (en la aplicación llamados 'temas'). Si el contexto no existe, lo crea. Permite especificar una descripción del contexto en caso que no exista."
      context_description:
        type: string
        maxLength: 255
        example: "Matemática I"
        description: "Opcional (si se utiliza, 'context_name' es requerido). Descripción del contexto, asociada al nombre único (context_name)."
  
  calendar_event:
    type: object
    properties:
      send_notification:
        type: integer
        example: 1
        enum: [0,1]        
        description: "Opcional. 1 = enviar notificacion, 0 = no enviar notificacion. Por defecto: 0"      
      global:
        type: integer
        example: 1
        enum: [0,1]
        description: "Opcional. 1 = novedades globales al servicio, 0 = no globales. Por defecto: 0"      
      event_name:
        type: string
        example: "Nuevo evento!"
        description: "Título o nombre del evento"
        maxLength: 150
      event_date:
        type: string
        example: "2017-10-01 15:30:00"
        description: "Fecha y hora del evento. Formato: Y-m-d H:i:s"
      event_duration:
        type: string
        example: "01:30:00"
        description: "Fecha y hora del evento. Formato: H:i:s"      
      event_description:
        type: string
        description: "Descripción del evento"
        example: "Esta es la descripción del nuevo evento"
        maxLength: 255
      event_location:
        type: string
        example: "Aula 3"
        description: "Lugar del evento"
        maxLength: 150
      updated_at:
        type: string
        example: '2017-08-25 00:10:11'
      created_at:
        type: string
        example: '2017-08-25 00:10:11'        
      id:
        type: integer
        example: 1134
  calendar_event_post_response:
    type: object
    properties:
      calendar_event:
        type: object
        $ref: '#/definitions/calendar_event'
      notification_push_data_uuid:
        type: string
        example: "e10adc-asda34-asdasdas-bbc"

  calendar_event_post:
    type: object
    required: 
    - event_name
    - event_date
    - event_description
    properties:
      event_name:
        type: string
        example: "Nuevo evento!"
        description: "Título o nombre del evento"
        maxLength: 150
      event_date:
        type: string
        example: "2017-10-01 15:30:00"
        description: "Fecha y hora del evento. Formato: Y-m-d H:i:s"
      event_duration:
        type: string
        example: "01:30:00"
        description: "Fecha y hora del evento. Formato: H:i:s"      
      event_description:
        type: string
        description: "Descripción del evento"
        example: "Esta es la descripción del nuevo evento"
        maxLength: 255
      event_location:
        type: string
        example: "Aula 3"
        description: "Lugar del evento"
        maxLength: 150
      global:
        type: integer
        example: 1
        enum: [0,1]
        description: "Opcional. 1 = eventos globales al servicio, 0 = no globales. Por defecto: 0"
      send_notification:
        type: integer
        example: 1
        enum: [0,1]        
        description: "Opcional. 1 = enviar notificacion, 0 = no enviar notificacion. Por defecto: 0"
      recipients:
        type: array
        items:
          type: string      
        example: ["id_externo_1", "id_externo_2", "id_externo_3"]
        description: "Opcional. Destinatarios: Arreglo de IDs de los destinatarios del evento. Los IDs son locales del servicio, los enviados al asociar el usuario (valores externos a Mi Universidad)"
      context:
        type: string
        maxLength: 150
        pattern: "^[a-zA-Z0-9_-]*$"
        example: "matematica_1"
        description: "Opcional. Nombre único (alfanunmérico y guiones) identificatorio del contexto (en la aplicación llamados 'temas'). Si el contexto no existe, lo crea. Para crear nuevos contextos, se recomienda utilizar los parámetros: context_name y context_description."
      context_name:
        type: string
        maxLength: 150
        pattern: "^[a-zA-Z0-9_-]*$"
        example: "matematica_1"
        description: "Opcional (si se utiliza, 'context_description' es requerido). Nombre único (alfanunmérico y guiones) identificatorio del contexto (en la aplicación llamados 'temas'). Si el contexto no existe, lo crea. Permite especificar una descripción del contexto en caso que no exista."
      context_description:
        type: string
        maxLength: 255
        example: "Matemática I"
        description: "Opcional (si se utiliza, 'context_name' es requerido). Descripción del contexto, asociada al nombre único (context_name)."
        
        
  InventoryItem:
    type: object
    required:
    - id
    - name
    - manufacturer
    - releaseDate
    properties:
      id:
        type: string
        format: uuid
        example: d290f1ee-6c54-4b01-90e6-d701748f0851
      name:
        type: string
        example: Widget Adapter
      releaseDate:
        type: string
        format: int32
        example: 2016-08-29T09:12:33.001Z
      manufacturer:
        $ref: '#/definitions/Manufacturer'
  Manufacturer:
    required:
    - name
    properties:
      name:
        type: string
        example: ACME Corporation
      homePage:
        type: string
        format: url
        example:  https://www.acme-corp.com
      phone:
        type: string
        example: 408-867-5309
# Added by API Auto Mocking Plugin
schemes:
 - https
# Added by API Auto Mocking Plugin
host: host
basePath: /api/v1
