#!/bin/sh
set -e
export TIMEZONE="America/Argentina/Buenos_Aires"
export APACHE_RUN_USER=${APACHE_RUN_USER:-www-data}
export APACHE_RUN_GROUP=${APACHE_RUN_GROUP:-www-data}
export MEMORY_LIMIT=${MEMORY_LIMIT:-'512M'}
export DB_SECRET="secret"
echo ${OAUTH_PRIVATE_KEY} > /app/storage/oauth-private.key
echo ${OAUTH_PUBLIC_KEY} > /app/storage/oauth-public.key
chown $APACHE_RUN_USER -R /app/storage
php artisan migrate:refresh
composer dump-autoload
exec "$@"
